[package]
name = "rust-vslam"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
nalgebra = "0.34.1"
opencv = "0.98.1"
rerun = "0.28.1"
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
rayon = "1.10"